// Change these with every release
#define PRODUCT_DATE	     "20 October 2001"
#define PRODUCT_VERSION      "4.00.2.0000"
#define PROD_VERSION_NUMBERS 4,0,2,0
#define FILE_VERSION	     PRODUCT_VERSION
#define FILE_VERSION_NUMBERS PROD_VERSION_NUMBERS

// These remain constant for the product
#define FILE_DESCRIPTION     "Advanced directory picker and file copier for the Wise Installation System"
#define PRODUCT_NAME	     "SHBffo (Shell_BrowseForFolder_FileOperation) - an advanced directory picker and file copier for the Wise Installation System"
#define INTERNAL_NAME	     "SHBffo"
#define ORIGINAL_FILENAME    "SHBffo.dll"
#define PRODUCT_DESCRIPTION  "Advanced directory picker and file copier for the Wise Installation System"
#define COPYRIGHT	     "Copyright © 2001 by Ralf Buschmann"

// These remain constant for your company
#define COMPANY		     "Herzog & Partner GmbH"
#define URL		     "http://www.backmagic.de"
